services:
  api:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - FLASK_ENV=${FLASK_ENV:-development}
      - API_PORT=${API_PORT:-5001}
      - MONGODB_DB=${MONGODB_DB:-users}
      - MONGODB_HOST=${MONGODB_HOST:-mongodb}
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


