name: Deply Render

on:
  push:
    branches: [ main ]  

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            pip install pytest
        
         
      - name: Run tests
        run: pytest -v --disable-warnings
      
