name: CI Tests and Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..30}; do
            if mongosh --host localhost:27017 --username admin --password admin --authenticationDatabase admin --eval "db.runCommand({ping: 1})" >/dev/null 2>&1; then
              echo "MongoDB is ready!"
              break
            fi
            echo "Attempt $i: MongoDB not ready yet..."
            sleep 2
          done

      - name: Verify MongoDB Connection
        run: |
          mongosh --host localhost:27017 --username admin --password admin --authenticationDatabase admin --eval "
            db.runCommand({ping: 1});
            db.runCommand({listDatabases: 1});
          "

      - name: Run tests
        run: pytest -v --disable-warnings --tb=short
        env:
          FLASK_ENV: testing
          GITHUB_ACTIONS: true
          MONGODB_DB: users_test
          MONGODB_HOST: localhost
          MONGODB_PORT: 27017
          MONGODB_USERNAME: admin
          MONGODB_PASSWORD: admin
          MONGODB_TEST_USERNAME: admin
          MONGODB_TEST_PASSWORD: admin 
